version: '3.4'

services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./data/db:/var/lib/postgresql/data
    
    ports:
      - "5000:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:

