# Generated by Django 3.2.8 on 2021-11-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivetreatment',
            name='result',
            field=models.TextField(blank=True, default='Cured', null=True),
        ),
        migrations.AlterField(
            model_name='testinfomation',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testinfomation',
            name='positivity',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
