# Generated by Django 3.2.8 on 2021-10-23 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_auto_20211023_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Danh Model'},
        ),
        migrations.AddField(
            model_name='testmodel',
            name='extra_name',
            field=models.CharField(default=None, editable=False, max_length=255),
        ),
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_content', to='hospital_app.testmodel')),
            ],
            options={
                'verbose_name_plural': 'Model X - 2021',
                'ordering': ('-created_at',),
            },
        ),
    ]
