# Generated by Django 3.2.8 on 2021-10-23 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_auto_20211023_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelx',
            name='test_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_content_x', to='hospital_app.testmodel'),
        ),
        migrations.CreateModel(
            name='ModelY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_content_y', to='hospital_app.testmodel')),
            ],
            options={
                'verbose_name_plural': 'Model Y - 2021',
                'ordering': ('-created_at',),
            },
        ),
    ]
