# Generated by Django 3.2.8 on 2021-10-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_auto_20211023_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modely',
            name='test_content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_content_y', to='hospital_app.testmodel'),
        ),
    ]
