# Generated by Django 3.2.8 on 2021-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_alter_modely_test_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='modely',
            name='sheet_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
