# Generated by Django 3.2.8 on 2021-10-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_modely_sheet_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.RemoveField(
            model_name='modely',
            name='test_content',
        ),
        migrations.DeleteModel(
            name='ModelX',
        ),
        migrations.DeleteModel(
            name='ModelY',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
