# Generated by Django 3.2.8 on 2021-10-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0011_auto_20211030_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
