# Generated by Django 3.2.8 on 2021-10-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_blog_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
