# Generated by Django 3.2.8 on 2021-11-02 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0018_auto_20211102_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='headofcamp',
            name='head_of_camp_id',
        ),
        migrations.RemoveField(
            model_name='headofcamp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='nurse_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('MALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='personal_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('HEAD', 'Head of camp')], default='STAFF', max_length=50),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('MALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='personal_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='phone',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='type',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('HEAD', 'Head of camp')], default='STAFF', max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='nurse',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('MALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AddField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='nurse',
            name='personal_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='nurse',
            name='phone',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AddField(
            model_name='nurse',
            name='type',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('HEAD', 'Head of camp')], default='STAFF', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('MALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('HEAD', 'Head of camp')], default='STAFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='admitted',
            name='personnel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.staff'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(choices=[('MALE', 'Male'), ('MALE', 'Female'), ('NOT PROVIDED', 'Not Provided')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.nurse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='receivetreatment',
            name='personal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor'),
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
