# Generated by Django 3.2.8 on 2021-11-02 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0019_auto_20211102_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='headofcamp',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='personal_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='personnel_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='headofcamp',
            name='personnel_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='nurse',
            name='personnel_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='personnel_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
    ]
