# Generated by Django 3.2.8 on 2021-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0020_auto_20211102_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
