# Generated by Django 3.2.8 on 2021-11-02 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0021_auto_20211102_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='first_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='last_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='phone',
            field=models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone',
            field=models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='staff',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')]),
        ),
    ]
