# Generated by Django 3.2.8 on 2021-11-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0022_auto_20211102_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='personnel_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
    ]
