# Generated by Django 3.2.8 on 2021-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0023_auto_20211102_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
    ]
