# Generated by Django 3.2.8 on 2021-11-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0024_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
