# Generated by Django 3.2.8 on 2021-11-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0025_auto_20211102_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nurse_id',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
