# Generated by Django 3.2.8 on 2021-11-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0029_auto_20211102_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='id',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
