# Generated by Django 3.2.8 on 2021-11-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0032_auto_20211102_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='number',
        ),
        migrations.RemoveField(
            model_name='history',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='medicationeffect',
            name='code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nurse_id',
        ),
        migrations.RemoveField(
            model_name='patientcomobidity',
            name='patient_number',
        ),
        migrations.RemoveField(
            model_name='receivetreatment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='receivetreatment',
            name='number',
        ),
        migrations.RemoveField(
            model_name='receivetreatment',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='number',
        ),
        migrations.RemoveField(
            model_name='testinfomation',
            name='number',
        ),
        migrations.DeleteModel(
            name='Admitted',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='MedicationEffect',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientComobidity',
        ),
        migrations.DeleteModel(
            name='ReceiveTreatment',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.DeleteModel(
            name='TestInfomation',
        ),
    ]
