# Generated by Django 3.2.8 on 2021-11-02 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0033_auto_20211102_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number_of_floors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('address', models.TextField(default=None)),
                ('phone', models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12)),
                ('first_name', models.CharField(default=None, max_length=25)),
                ('last_name', models.CharField(default=None, max_length=25)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('HEAD', 'Head of camp')], default='STAFF', max_length=50)),
                ('personnel_id', models.CharField(default=None, editable=False, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('number', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(default=None, editable=False, max_length=50, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid phone number (Vietnamese only)', regex='^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT PROVIDED', 'Not Provided')], default='NOT PROVIDED', max_length=12)),
                ('address', models.TextField()),
                ('identify_number', models.IntegerField()),
                ('nurse_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='TestInfomation',
            fields=[
                ('test_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=10)),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('positivity', models.BooleanField()),
                ('type', models.CharField(choices=[('PCR', 'PCR test'), ('Quick', 'Quick test'), ('SPO2', 'SPO2 test'), ('Resp.', 'Respiratory rate')], max_length=50)),
                ('condition', models.TextField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('symptom_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('symptom_name', models.CharField(max_length=50)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('maximum_capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Normal', 'Normal room'), ('Emergency', 'Emergency room'), ('Recuper.', 'Recuperation room')], max_length=50)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.building')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('result', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.medication')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('personal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientComobidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationEffect',
            fields=[
                ('effect_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.medication')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('destination_room', models.CharField(max_length=50)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.staff')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.testinfomation')),
            ],
        ),
    ]
