# Generated by Django 3.2.8 on 2021-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0034_admitted_building_history_medication_medicationeffect_nurse_patient_patientcomobidity_receivetreatme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcomobidity',
            name='id',
        ),
        migrations.AddField(
            model_name='patientcomobidity',
            name='comobidity_name',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
