# Generated by Django 3.2.8 on 2021-11-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0035_auto_20211102_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nurse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.nurse'),
        ),
    ]
