# Generated by Django 3.2.8 on 2021-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0036_alter_patient_nurse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomobidity',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientcomobidity',
            name='comobidity_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
