# Generated by Django 3.2.8 on 2021-11-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0037_auto_20211102_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientComobidity',
        ),
    ]
