# Generated by Django 3.2.8 on 2021-11-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0039_patientcomobidity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientComobidity',
        ),
    ]
