# Generated by Django 3.2.8 on 2021-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0045_auto_20211102_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcomobidity',
            name='id',
        ),
        migrations.AlterField(
            model_name='patientcomobidity',
            name='comobidity_name',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
