# Generated by Django 3.2.8 on 2021-11-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0047_auto_20211102_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfomation',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testinfomation',
            name='test_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
    ]
