# Generated by Django 3.2.8 on 2021-11-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0050_auto_20211102_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admitted',
        ),
        migrations.DeleteModel(
            name='TestInfomation',
        ),
    ]
