# Generated by Django 3.2.8 on 2021-11-02 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0053_auto_20211102_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfomation',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('test_id', models.CharField(default=None, editable=False, max_length=50, null=True)),
                ('value', models.CharField(max_length=10)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('positivity', models.BooleanField()),
                ('type', models.CharField(choices=[('PCR', 'PCR test'), ('Quick', 'Quick test'), ('SPO2', 'SPO2 test'), ('Resp.', 'Respiratory rate')], max_length=50)),
                ('condition', models.TextField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.staff')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.testinfomation')),
            ],
        ),
    ]
