# Generated by Django 3.2.8 on 2021-11-03 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0054_admitted_testinfomation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='symptom_id',
        ),
        migrations.AddField(
            model_name='symptom',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient'),
        ),
        migrations.AlterField(
            model_name='testinfomation',
            name='type',
            field=models.CharField(choices=[('PCR', 'PCR test'), ('QUICK', 'Quick test'), ('SPO2', 'SPO2 test'), ('RESP.', 'Respiratory rate')], max_length=50),
        ),
    ]
