# Generated by Django 3.2.8 on 2021-11-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0055_auto_20211103_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='symptom_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
    ]
