# Generated by Django 3.2.8 on 2021-11-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0056_symptom_symptom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='number',
            new_name='patient_number',
        ),
    ]
