# Generated by Django 3.2.8 on 2021-11-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0057_rename_number_symptom_patient_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='patient_number',
            new_name='number',
        ),
    ]
