# Generated by Django 3.2.8 on 2021-11-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0058_rename_patient_number_symptom_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
