# Generated by Django 3.2.8 on 2021-11-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0059_auto_20211103_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('NORMAL', 'Normal room'), ('EMERGENCY', 'Emergency room'), ('RECUP.', 'Recuperation room')], max_length=50),
        ),
    ]
