# Generated by Django 3.2.8 on 2021-11-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0060_auto_20211103_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcomobidity',
            name='comobidity_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
