# Generated by Django 3.2.8 on 2021-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0061_alter_patientcomobidity_comobidity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomobidity',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientcomobidity',
            name='comobidity_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
