# Generated by Django 3.2.8 on 2021-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0063_remove_patientcomobidity_comobidity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomobidity',
            name='comobidity_name',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
