# Generated by Django 3.2.8 on 2021-11-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0064_patientcomobidity_comobidity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcomobidity',
            name='comobidity_name',
        ),
    ]
