# Generated by Django 3.2.8 on 2021-11-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0069_auto_20211103_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientComobidity',
        ),
    ]
