# Generated by Django 3.2.8 on 2021-11-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0070_delete_patientcomobidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientComobidity',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('comobidity_name', models.CharField(default=None, max_length=50, unique=True)),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
            ],
        ),
    ]
