# Generated by Django 3.2.8 on 2021-11-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0071_patientcomobidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcomobidity',
            name='comobidity_name',
            field=models.CharField(max_length=50),
        ),
    ]
