# Generated by Django 3.2.8 on 2021-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0073_alter_patientcomobidity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcomobidity',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
