# Generated by Django 3.2.8 on 2021-11-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0074_alter_patientcomobidity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medicationeffect',
            name='effect_name',
        ),
        migrations.AddField(
            model_name='medication',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationeffect',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
