# Generated by Django 3.2.8 on 2021-11-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0075_auto_20211103_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history_id',
        ),
        migrations.AddField(
            model_name='history',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationeffect',
            name='effect_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationeffect',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
