# Generated by Django 3.2.8 on 2021-11-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0077_alter_history_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='number',
            new_name='patient_number',
        ),
        migrations.RenameField(
            model_name='receivetreatment',
            old_name='number',
            new_name='patient_number',
        ),
    ]
