# Generated by Django 3.2.8 on 2021-11-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0078_auto_20211103_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='number',
            new_name='patient_number',
        ),
    ]
