# Generated by Django 3.2.8 on 2021-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0079_rename_number_symptom_patient_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationeffect',
            name='code',
        ),
        migrations.RemoveField(
            model_name='receivetreatment',
            name='medication_code',
        ),
    ]
