# Generated by Django 3.2.8 on 2021-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0083_auto_20211103_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
