# Generated by Django 3.2.8 on 2021-11-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0085_auto_20211103_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='building_name',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
