# Generated by Django 3.2.8 on 2021-11-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0086_auto_20211103_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=50)),
                ('number_of_floors', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='building_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.building'),
            preserve_default=False,
        ),
    ]
