# Generated by Django 3.2.8 on 2021-11-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0087_auto_20211103_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='building_name',
        ),
    ]
