# Generated by Django 3.2.8 on 2021-11-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0090_auto_20211103_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
