# Generated by Django 3.2.8 on 2021-11-03 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0091_delete_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=50)),
                ('number_of_floors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('maximum_capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('NORMAL', 'Normal room'), ('EMERGENCY', 'Emergency room'), ('RECUP.', 'Recuperation room')], max_length=50)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.building')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_room', models.CharField(max_length=50)),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.room')),
            ],
        ),
    ]
