# Generated by Django 3.2.8 on 2021-11-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0092_building_history_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id',
        ),
    ]
