# Generated by Django 3.2.8 on 2021-11-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0093_rename_room_id_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
