# Generated by Django 3.2.8 on 2021-11-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0096_history_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
    ]
