# Generated by Django 3.2.8 on 2021-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0097_auto_20211103_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
    ]
