# Generated by Django 3.2.8 on 2021-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0098_auto_20211103_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headofcamp',
            name='type',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='type',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True),
        ),
    ]
