# Generated by Django 3.2.8 on 2021-11-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0100_auto_20211103_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitted',
            name='number',
        ),
        migrations.AddField(
            model_name='admitted',
            name='patient_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.patient'),
        ),
        migrations.AlterField(
            model_name='admitted',
            name='personnel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.staff'),
        ),
        migrations.AlterField(
            model_name='admitted',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.testinfomation'),
        ),
    ]
