# Generated by Django 3.2.8 on 2021-11-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0102_auto_20211103_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admitted',
            old_name='personnel_id',
            new_name='staff_id',
        ),
    ]
