# Generated by Django 3.2.8 on 2021-11-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0103_rename_personnel_id_admitted_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.building'),
        ),
    ]
