# Generated by Django 3.2.8 on 2021-11-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0104_alter_room_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nurse_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.nurse'),
        ),
        migrations.AlterField(
            model_name='receivetreatment',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.doctor'),
        ),
        migrations.AlterField(
            model_name='receivetreatment',
            name='medication_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.medication'),
        ),
        migrations.AlterField(
            model_name='receivetreatment',
            name='patient_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.patient'),
        ),
    ]
